repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0            # Version of the hooks repo
    hooks:
      - id: trailing-whitespace      # Removes unnecessary whitespace at the end of lines
      - id: end-of-file-fixer        # Ensures files end with a newline character

  - repo: https://github.com/psf/black
    rev: 24.3.0            # Version of Black (Python code formatter)
    hooks:
      - id: black                    # Runs Black to auto-format Python files

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0            # Version of isort (sorts Python imports)
    hooks:
      - id: isort                    # Re-orders and formats Python import statements

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0            # Version of flake8 (Python linter)
    hooks:
      - id: flake8                   # Checks Python code for style and quality issues

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1            # Version of mypy (type checker)
    hooks:
      - id: mypy                     # Runs static type checking
